### ISSUE TITLE
Comments on the installation procedure

### ISSUE THREAD

**Issue by Luke192** [fatso83/vmware-auto-suspend#7]
Hi Carl-Erik,

Thanks for providing this repo. I had a couple of issues when installing it though, which I though I'd feed back to you. Firstly, when I ran the schtasks command I got the following error message...

ERROR: The task XML is malformed.
(1,2)::ERROR: incorrect document syntax

To get around this, I removed the first three non-ASCII bytes from the file (the ones that identify the encoding before the <?xml starts). That fixed that issue. But then I got...

ERROR: Access is denied.

... because I wasn't running the prompt with admin privileges, so that might be worth mentioning in the readme.

Hope that helps and thanks again,

Luke.

**Comment by DavidSchargel** [comment]
You may want to also check https://github.com/fatso83/vmware-auto-suspend/issues/5#issuecomment-650758368 for an encoding solution that worked for me. Perhaps these should both be mention in the future readme.

**Comment by fatso83** [comment]
Hi, I had a 3 weeks long holiday, so sorry for the late reply. Thanks for bringing this to my attention (again). I looked into why this was happening and it was a mismatch between the file's actual encoding (utf8) and the line where it actually said which encoding it used (utf16).

```
$ xmllint vmware-auto-suspend.xml 
vmware-auto-suspend.xml:1: parser error : Document labelled UTF-16 but has UTF-8 content
<?xml version="1.0" encoding="UTF-16"?>
```

 Fixed this in the latest version :) Thanks!

**Comment by gaasedelen** [comment]
FYI this is still an issue on master.

I ended up just deleting the encoding line entirely and it no longer complained about the XML being malformed ¯\\_ (ツ) _/¯

**Comment by fatso83** [comment]
Hmm ... this is 100% valid now, as this check shows, but maybe Windows does not handle the BOM (byte order mark)?

```bash
$ file vmware-auto-suspend.xml && (xmllint vmware-auto-suspend.xml > /dev/null && echo "Linting OK")
vmware-auto-suspend.xml: XML 1.0 document, UTF-8 Unicode (with BOM) text, with very long lines, with CRLF line terminators
Linting OK
```

I'll try and research if this happens on my Windows machine, and if so, fix that, but right now everything looks valid.

**Comment by fatso83** [comment]
Hi, indeed you were right. SCHTASKS uses some kind of wonky XML reader that does not respect the encoding set. Simply using `xmllint` did not show this behaviour, unfortunately. `schtasks` only accepted UTF-16 LE (little endian) and ANSI. I tried various other  encodings, but ended up removing the encoding altogether in the end, as @gaasedelen did.

**Comment by fatso83** [comment]
Fixed this using an install script to avoid the issue :)
https://github.com/fatso83/vmware-auto-suspend#installing
